profile_schema_version: 1

name: Development Environment
id: dev
version: 1
description: My development workstation setup

tags:
  - development

supported_os:
  - fedora
  - windows

packages:
  all:
    - git
    - vscode

  fedora:

  windows:
    - win_terminal
